name: adminpanel
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  get: ^4.6.6
  fl_chart: ^0.69.2
  intl: ^0.19.0
  file_picker: ^8.0.0+1
  http: ^1.2.0
  logger: ^2.5.0
  dio: ^5.8.0+1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
        - assets/images/
